name: Sync Fork

on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          repository: oguzcandemir/NERV
          ref: paradigm
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        run: git remote add upstream https://github.com/oguzcandemir/NERV.git

      - name: Fetch upstream
        run: git fetch upstream        
        
      - name: Set Git identity
        run: git config user.name "github-actions[bot]"
      
      - name: Set Git identity 2
        run: git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream
        run: git merge upstream/paradigm --allow-unrelated-histories -m "Merge upstream paradigm"

      - name: Push changes
        run: git push origin paradigm
